// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/textures/Diamond.tsx": () => import("../components/mockups/textures/Diamond.tsx"),
  "./components/mockups/textures/Grain.tsx": () => import("../components/mockups/textures/Grain.tsx"),
  "./components/mockups/textures/Grill.tsx": () => import("../components/mockups/textures/Grill.tsx"),
  "./components/mockups/textures/Kraft.tsx": () => import("../components/mockups/textures/Kraft.tsx"),
  "./components/mockups/textures/Smoke.tsx": () => import("../components/mockups/textures/Smoke.tsx")
};
